// Code generated by hotswap. DO NOT EDIT.

package woof

import (
	"github.com/edwingeng/hotswap/demo/slink/plugin/dog/hotswapbureau"
)

func init() {
	hotswapbureau.RegisterFunc("live_Woof", live_Woof)
}
