// Code generated by hotswap. DO NOT EDIT.

package dog

import (
	"github.com/edwingeng/hotswap/demo/slink/plugin/dog/hotswapbureau"

	_ "github.com/edwingeng/hotswap/demo/slink/plugin/dog/woof"
)

func HotswapLiveFuncs() map[string]interface{} {
	return hotswapbureau.LiveFuncs
}

func HotswapLiveTypes() map[string]func() interface{} {
	return hotswapbureau.LiveTypes
}
