// Code generated by hotswap. DO NOT EDIT.

package {{.PackageName}}

import (
	"{{.BureauPackagePath}}"
)

func init() {
{{- range .LiveFuncs }}
	hotswapbureau.RegisterFunc("{{.}}", {{.}})
{{- end}}

{{- range .LiveTypes }}
	hotswapbureau.RegisterType("{{.}}", func() interface{} {
		return &{{.}}{}
	})
{{- end}}
}
