// Code generated by hotswap. DO NOT EDIT.

package hotswapbureau

import (
	"fmt"
)

var (
	LiveFuncs = make(map[string]interface{})
	LiveTypes = make(map[string]func() interface{})
)

func RegisterFunc(name string, fn interface{}) {
	if _, ok := LiveFuncs[name]; !ok {
		LiveFuncs[name] = fn
		return
	}
	panic(fmt.Errorf("%q is already registered", name))
}

func RegisterType(name string, fn func() interface{}) {
	if _, ok := LiveTypes[name]; !ok {
		LiveTypes[name] = fn
		return
	}
	panic(fmt.Errorf("%q is already registered", name))
}
